from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel

from gmxflow.config import GmxFlowConfig
from gmxflow.topology import reset_molecules_lines


class SmallMoleculeComplexResult(BaseModel):
    complex_gro: Path
    topology: Path
    marker: Path
    protein_atoms: int
    ligand_atoms: int


def assemble_small_molecule_complex(
    config: GmxFlowConfig,
    project_root: Path,
) -> SmallMoleculeComplexResult:
    project_root = project_root.expanduser().resolve()
    topo = project_root / "work" / "topo"
    ligand_dir = project_root / "work" / "ligand"
    ligand_prefix = config.input.ligand_resname.lower()

    protein_gro = topo / "protein.gro"
    ligand_pdb = ligand_dir / f"{ligand_prefix}_ini.pdb"
    ligand_itp = ligand_dir / f"{ligand_prefix}.itp"
    ligand_prm = ligand_dir / f"{ligand_prefix}.prm"
    topol_top = topo / "topol.top"
    complex_gro = topo / "complexo.gro"
    marker = topo / ".small_molecule_complex.ok"

    for path in (protein_gro, ligand_pdb, ligand_itp, ligand_prm, topol_top):
        if not path.is_file():
            raise FileNotFoundError(f"Arquivo necessário não encontrado: {path}")

    protein = _read_gro(protein_gro)
    ligand_lines = _ligand_pdb_to_gro_lines(
        ligand_pdb,
        resname=config.input.ligand_resname,
        start_atom_index=len(protein.atom_lines) + 1,
        residue_number=_next_residue_number(protein.atom_lines),
    )
    _write_gro(
        path=complex_gro,
        title="Protein-ligand complex generated by gmxflow",
        atom_lines=[*protein.atom_lines, *ligand_lines],
        box_line=protein.box_line,
    )
    _update_topology(
        topol_top=topol_top,
        ligand_resname=config.input.ligand_resname,
        ligand_prm="../ligand/" + ligand_prm.name,
        ligand_itp="../ligand/" + ligand_itp.name,
        transient_molecules={
            config.input.ligand_resname,
            config.solvent.positive_ion,
            config.solvent.negative_ion,
            "SOL",
        },
    )
    marker.write_text(
        "\n".join(
            [
                "small_molecule_complex: ok",
                f"complex_gro: {complex_gro}",
                f"topology: {topol_top}",
                f"ligand_resname: {config.input.ligand_resname}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return SmallMoleculeComplexResult(
        complex_gro=complex_gro,
        topology=topol_top,
        marker=marker,
        protein_atoms=len(protein.atom_lines),
        ligand_atoms=len(ligand_lines),
    )


class _GroFile(BaseModel):
    title: str
    atom_lines: list[str]
    box_line: str


def _read_gro(path: Path) -> _GroFile:
    lines = path.read_text(encoding="utf-8").splitlines()
    if len(lines) < 3:
        raise ValueError(f"Arquivo .gro inválido: {path}")
    try:
        atom_count = int(lines[1].strip())
    except ValueError as error:
        raise ValueError(f"Contagem de átomos inválida em {path}") from error
    atom_lines = lines[2 : 2 + atom_count]
    if len(atom_lines) != atom_count:
        raise ValueError(f"Arquivo .gro truncado: {path}")
    box_line_index = 2 + atom_count
    if box_line_index >= len(lines):
        raise ValueError(f"Arquivo .gro sem linha de caixa: {path}")
    return _GroFile(title=lines[0], atom_lines=atom_lines, box_line=lines[box_line_index])


def _write_gro(path: Path, title: str, atom_lines: list[str], box_line: str) -> None:
    path.write_text(
        "\n".join([title, f"{len(atom_lines):5d}", *atom_lines, box_line, ""]),
        encoding="utf-8",
    )


def _ligand_pdb_to_gro_lines(
    ligand_pdb: Path,
    resname: str,
    start_atom_index: int,
    residue_number: int,
) -> list[str]:
    lines: list[str] = []
    atom_index = start_atom_index
    for record in ligand_pdb.read_text(encoding="utf-8").splitlines():
        if not record.startswith(("ATOM", "HETATM")):
            continue
        atom_name = record[12:16].strip()
        x = float(record[30:38]) / 10
        y = float(record[38:46]) / 10
        z = float(record[46:54]) / 10
        lines.append(
            f"{residue_number % 100000:5d}{resname[:5]:<5}{atom_name[:5]:>5}"
            f"{atom_index % 100000:5d}{x:8.3f}{y:8.3f}{z:8.3f}"
        )
        atom_index += 1
    if not lines:
        raise ValueError(f"Ligante sem registros ATOM/HETATM: {ligand_pdb}")
    return lines


def _next_residue_number(atom_lines: list[str]) -> int:
    residue_numbers = []
    for line in atom_lines:
        try:
            residue_numbers.append(int(line[:5]))
        except ValueError:
            continue
    return (max(residue_numbers) + 1) if residue_numbers else 1


def _update_topology(
    topol_top: Path,
    ligand_resname: str,
    ligand_prm: str,
    ligand_itp: str,
    transient_molecules: set[str],
) -> None:
    lines = topol_top.read_text(encoding="utf-8").splitlines()
    lines = _insert_include_after_forcefield(lines, ligand_prm)
    lines = _insert_include_before_system(lines, ligand_itp)
    lines = _ensure_molecule(lines, ligand_resname, transient_molecules)
    topol_top.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _insert_include_after_forcefield(lines: list[str], include_path: str) -> list[str]:
    include_line = f'#include "{include_path}"'
    if include_line in lines:
        return lines
    output: list[str] = []
    inserted = False
    for line in lines:
        output.append(line)
        if not inserted and "forcefield.itp" in line and line.strip().startswith("#include"):
            output.append(include_line)
            inserted = True
    if not inserted:
        output.insert(0, include_line)
    return output


def _insert_include_before_system(lines: list[str], include_path: str) -> list[str]:
    include_line = f'#include "{include_path}"'
    if include_line in lines:
        return lines
    for index, line in enumerate(lines):
        if line.strip() == "[ system ]":
            return [*lines[:index], include_line, "", *lines[index:]]
    return [*lines, "", include_line]


def _ensure_molecule(
    lines: list[str],
    ligand_resname: str,
    transient_molecules: set[str],
) -> list[str]:
    return reset_molecules_lines(
        lines,
        remove_molecules=transient_molecules,
        append_molecules=[(ligand_resname, 1)],
    )
